---
- name: OpenVPN | Harden Services | cron.allow
  copy:
    content: "root"
    dest: "/etc/cron.allow"
    owner: root
    group: root
    mode: 0644

# Note aide package on debian requires parts of exim, so can't uninstall it. just disable.
- name: OpenVPN | Harden Services | Disable mail services
  service:
    name: "{{ item }}"
    enabled: false
  register: unused_disable
  #If the service doesn't exist, no need to disable -> not a failure
  failed_when: "unused_disable is failed and ('find' not in unused_disable.msg and 'found' not in unused_disable.msg)"
  with_items:
    - exim4
    - postfix
